### PR TITLE
Javascript & HTML Refactor

### PR DESCRIPTION
**Pull request by Harkoni**
Removed a bunch of duplicate code/html lines. Tried making the system easier to read. Also drastically cut down the number of times that damage is recalculated to display the table once.

Also fixed an error that makes all damage ranges always count the weapon as being awakened. To see this in 0.3.1 select the black belt sword and shield and target silver Rathalos, it will incorrectly show 5 as the minimum damage while the true minimum is 3. This is because while it may not be displaying the thunder elemental damage it does count it for comparing ranges.

Try it out, see if I broke anything. From my random testing it appears identical to the current live site, which is a good sign when making major back end changes.

### CODE REVIEW

**Comment by mrmin123** [comment]
Awesome! Thanks for reducing the number of calls to the calcDamage function. I thought it was absurd that I had to call it that many times, but didn't know you could return an object into the template. That simplifies things greatly.

I was going to change the modifiers list to an ng-repeat solution with the update to add URL parameters support, but it looks like you went and did that for me. Much appreciated.

**Comment by mrmin123** [comment]
I also need to re-write the weapon information miner to take info from the Android App DB instead of Kiranico. I'm planning on moving the weapon multiplier information to the weapon_type JSON then, because yes, all weapons of the same type seem to have the same multiplier.

**Comment by bd4** [comment]
What info do you need for each weapon? I have a lot of python scripts for accessing the db, in https://github.com/bd4/monster-hunter-scripts. I've been meaning to write a script to dump it out as static JSON that mimics an API. E.g. /weapon/Sharq Assawlt.json would contain all the info about that weapon. Simplest thing would be to just dump all the columns from the db.

Also thanks for the weapon_type JSON, I've been using that in a script that compares damage of different weapons against a monster. I average across all motion values to get some sense of how important element is for the weapon, and use different weighted averages across the monster hitboxes to get a single value.

**Comment by Harkoni** [comment]
Glad to help. Good luck with the URL parameters. Those will make testing(at least for me) considerably easier as I'll be able to just save off what setup I am testing with and confirm results without manually doing that over and over.

Glad to here you are using the android DB for weapon data(Kiranico has a problem with part of their bowgun info unless you are viewing it from the 'weapon overview page'(The one that lists all weapons of that type)).

I see you've already switched monster data on to that as well. But here's something we may want to think about that I came across this myself when writing up the monster entries on my spreadsheet. The android app (in almost all cases) duplicates all hitzones if any hit zone changes based on a state. What I mean by this is that if a monster has parts that change damage resists based on enrage or being broken then the app will list all parts(even the ones that don't change in that state) twice(3 times if they change on enrage & broken). My suggestion would be to process the data from the app DB and for monsters with parts that change on state and add a drop down to our damage chart that uses only entries from that state(or remove the non changing parts and redisplay them along with the changed parts) rather than have the damage grid have twice as many columns.

(As a side note we may want to make 'part broken' not be a state and instead always be an option on parts that can break(check box or something to swap out the column with the broken column) and reference the modified(if it changes) damage profile for that column if the option is set.)

**Comment by mrmin123** [comment]
@bd4 Since only blademaster weapons are supported right now, just stuff like sharpness values, attack, weapon class, affinity, etc. I already have a miner for the monsters from the db so it's just a matter of implementing the queries to get data from the sqlite db, and converting things like the sharpness values so they match the format of what was in Kiranico (since the current UI is fit for that data). The pre-0.3.0 version of this tool used a simple API to get info just for the one weapon, but I went with the method of caching the whole JSON as you suggested in the reddit thread. Saved me the trouble of having a backend entirely!

@Harkoni On the subject of weapon data, I'm actually not sure what information you need for the bowgun/bow damage calculations. Previously I pulled what was called the 'bowgun config' from Kiranico but I don't know if that's useful or not. Could you let me know?

Also, thanks for bringing up the monster state thing. Ever since pulling in the mh4u.db information the way the columns have been scrunching up has irked me somewhat. The dropdown for the different states is a good idea. On the fence on the individual checks for broken state or not, but I guess it could work.

**Comment by bd4** [comment]
Ya the way they store monster hitzone data is awkward to deal with. I parse the hitzone names and treat the parens as different state for a single zone. So far I've seen "Part Broken" and "Enraged", and "Cover Hide Broken" which I think is basically the same as "Part Broken", although it may cross hit zones. It also includes those even when damage doesn't change, and some breakable hitzones don't change damage, so I try to guess breakable parts by looking at the hunting rewards.

I like the idea of having drop downs with different states and a checkbox for broken/not broken on each part.

What about something like this for monster data and hitzones?
    {
       "name": "Basarios",
       ...
       "hitzones": [{
             "part": "Chest",
             "breakable": True,
             "states": [{
                   "state": "Normal",
                   "cut": 25,
                   "impact": XX,
                   "water": 20,
                   .. },
             { "state": "Broken",
               "cut":  XX,
               "water": XX"
             }]
    }
             

I've noticed that some item names have non-ascii chars and some have '/' which is awkward when using names in the URLs. I'm debating using the IDs instead, vs URL encoding all the names. The nice thing about using names is that you can define a dropdown based on the names, and there is no need to also keep track of an id when requesting more details about the chosen monster. Or is there an easy way to handle dropdowns and autocomplete textfields in JavaScript with (id, name) paris?

**Comment by Harkoni** [comment]
@mrmin123 The bowgun config you pulled is just about the only real data that I need but the version you currently have is kind of wrong(Kiranico's fault). That data is the clip size for each type of shot which is very useful for me to have(planning on showing only shot you can shoot, eventually including the armor skills for that as well, unless you check the 'show unfirable shot types' option(or something similar). The problem with Kiranico's data is that it doesn't differentiate between shot types that are firable always and those that are only firable with skills, at least not on the individual weapon pages. On the heavy/light bowgun overview pages it shows the 'need a skill to fire this type' numbers in parenthesis but on the individual pages it does not show that at all. If we can get those numbers in parenthesis and represent them as negative numbers that would be the easiest to work with for me. Beyond that data, I would like(although not necessary for the first implementation), the siege/rapid fire data(not sure the app has this data, kiranico does the ammo types marked with the * on the individual pages, or in their own column on the overview pages), the reload speed and recoil(think the app stores these as numbers which is fine), the weapon rarity(this is really not all that important but would allow me to only enable the 'remove limiter' for guns that can have the limiter removed.)

@bd4 That would be pretty much exactly what I'd like see although we may want to include an array of possible states for the monster(probably generated by walking the parts list and finding all unique states) for easier access for a possible dropdown.

**Comment by bd4** [comment]
Ya having a top level list of states for the monster would be useful, and easy enough to add. I have a lot of the code already for parsing hitbox and weapon sharpness data from the db, I can take a stab at generating JSON tonight.

**Comment by bd4** [comment]
Looked more closely at your current JSON formats, the single file for all monsters/weapons seems to work well enough. What are you using to generate that currently, and which parts are based on kiranico and which on the android db? I'd be happy to help with stuff since I already have so much related code, and I have a side agenda I've trying to create a standard set of JSON files, but don't want to duplicate effort either. Would be great to have the JSON generation scripts available somewhere in a github repo too.

**Comment by Harkoni** [comment]
Oh, while I still have it in mind, I think there is something funky with the great sword elemental calculation. This might just be a failure in my knowledge but I didn't think that charge attacks had such a high multiplier on the elemental damage. Ignoring that though, there was a strange modifier being passed in to the 'modmul' parameter for great sword charge attacks. It was adding either +1 (for charge level 2) or +2(for charge level 3) This strikes me as strange because it looked like an attempt to do the 2x or 3x multiplier that was already being done to the elementalPower value. The other thing to note is that the function caps modmul at .2 maximum(since that is what the % multiplier caps at when combining elemental atk up and specific elemental atk up). I removed the +1 and +2 in my merge but figured I'd ask about it just to see.

**Comment by mrmin123** [comment]
Quick check in between meetings so haven't had a chance to read everything but:
@Harkoni The modmul part is most likely an error. The 2x and 3x was based off of this reply: http://www.reddit.com/r/MonsterHunter/comments/31ywkm/introducing_the_calculating_palico_beta_an_online/cqa8gpl?context=3
Not sure how accurate this is, but it's the only info I have. Feel free to correct. I think I added the +1 and +2, remembered that modmul is capped at 0.2, and went back and multiplied the raw attack by 2x and 3x to bypass the cap while forgetting to remove the +1 and +2 to modmul. The elemental modifier might be incorrect to begin with, but the +1 and +2 should not have been removed; thanks for catching that.

**Comment by mrmin123** [comment]
Also I rewrote the monster data miner earlier during my lunch break but didn't have a chance to look at the output. I'll upload the miner and the resulting json and see what you guys think after my next meeting.

**Comment by mrmin123** [comment]
Hey guys, the scraper can be found [here](https://github.com/mrmin123/the-calculating-palico/blob/master/_scrape_monsters.py). Uploaded the output to [here](http://minyoung.ch/calculatingpalico/json/monster_data_new.json). Let me know what you think.

**Comment by bd4** [comment]
I prefer having a dictionary for the part damage instead of a list, because it's hard to understand the list data without context (which is cut/impact/fire etc). Probably not necessary for this project, but it makes it easier to understand for new developers. Also a nice trick with sqlite so you don't have to use positional indexes in db rows:

    conn.row_factory = sqlite3.Row

makes the code easier to read. Documented here: https://docs.python.org/2/library/sqlite3.html#row-objects

I ended up heavily re-factoring my db code and data model, in a way that makes it pretty easy to generate JSON for various things and customize it, including creating index files for easily slicing the data in different ways. I'm curious if you would be interested in migrating to something like this. I'm also open to changes to format and structure. I guess it would be a pain to migrate ids and data format, but converging on some standard could be useful.

Instead of using a single file with all the data, I have a directory for each entity type: http://mhapi.info/jsonapi/

I could generate monolithic data (one file with all entity data) as well, but I find it's easier to audit when using separate files. I guess it is a little extra work client side to have to load the item each time with AJAX, instead of one AJAX and in memory access. But efficiency wise the browser will cache the files in both cases. Marginally faster page load with separate files as well, with finer grained cache invalidation if there is an error in the data and only one or two files need updating. That is probably bike shedding a bit though, the data is so small it doesn't matter that much either way. I'm open to maintaining both, it's very easy to do.

Here's what I have for monster data with damage:
http://mhapi.info/jsonapi/monster/64.json

'Default' is probably a better name than 'Normal', I think I'll change that. I have the data in Part->State hierarchy, in nested dicts. That is most convenient for me in my Python app, because I average over states (with different weights) across a single part to get a single number. The JSON is generated based on the Python data model.

I also generate lists for each entity:
http://mhapi.info/jsonapi/weapon/_list.json
and indexes for mapping name->id or getting a list of all weapons of a certain type (wtype in the db):
http://mhapi.info/jsonapi/weapon/_index.json
the index stuff is more experimental, not sure what is most useful there yet.

My main motivation for doing this is that I want to change Poogie Recommends from using text files to using JSON and a nice HTML UI, where you can click on quests or monsters to get details, without having to go look it up elsewhere. And that got me thinking that it would be easy to do similar things for weapons and all the other data in the db.

Here's the script that generates the json:
https://github.com/bd4/monster-hunter-scripts/blob/master/bin/mkjsonapi.py

This is my damage program, it's command line Python and designed to compare several weapons of the same class against a monster:
https://github.com/bd4/monster-hunter-scripts/blob/master/bin/mhdamage.py
I didn't try to duplicate what palico does so well, just experimenting with ways of flattening the data for easy comparison.

**Comment by mrmin123** [comment]
@bd4 Sorry for the late response! Work has been relentless the last few days.

Thanks for the tip on sqlite. I'm coming from psycopg2 where you have to load a separate library to return dictionaries. Good to see the sqlite3 library has that built-in.

On the use of dictionaries vs lists for storing the values, I think because the JSON being generated and served by this app is so specific to its own use I think it's fine. Being able to access the hit/elemental types as integer locations also lets me do things like having a simple ng-if="element < 6" in the html to not show the elemental damage for abnormal status effect attacks, instead of having to check against each type to include or exclude. More difficult to interpret coming in from the outside, but self evident once you do the research on where the information was sourced from, and allows for a slightly leaner code. It's also data that will theoretically almost never change once complete, so I'm not all that worried about having to moving the structure around in the future. If someone wants a more general-use source of the information, they should probably use the API you've cooked up :)

**Comment by bd4** [comment]
Ok makes sense, it is really easy to generate app specific JSON from various sources.

I think I'm going to end up maintaining a fork of the sqlite db, and work to gradually get improvements included upstream into the google spreadsheets they use to maintain it in the Android project. I already submitted a set of changes but they are very busy adding new features, so not sure how quickly the changes will get included. Let me know if you find an error/omissions, and if you have ideas for improving the schema. I will probably end up restructure the damage data, munging it on the fly is more complicated than having a script to update it once in the db.

**Comment by mrmin123** [comment]
Someone recently commented on the reddit thread that the mh4u db source is actually missing the Gogmazios and Fatalis damage information. It's definitely not in both the Android app db and Ping's Dex, but Kiranico seems to have it. I think that's the only stuff that's missing that I'm aware of, but I still haven't had a chance to look at the weapon data :(

**Pull request merged**
